AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda function by using AWS SAM.
Globals:
  Function:
    MemorySize: 256
    Runtime: python3.6
    Timeout: 15
Resources:
  SamSampleLambda:
    Properties:
      CodeUri: s3://yueguchi-sam-sample/0abb0163ad5ce938808c30d02af9408d
      Events:
        Timer:
          Properties:
            Schedule: rate(5 minutes)
          Type: Schedule
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::569113468865:role/lambda_dynamo
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
