AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda function by using AWS SAM.

Globals:
  Function:
    Runtime: python3.6
    Timeout: 15
    MemorySize: 256
    #Environment:
    #  Variables:
    #    TABLE_NAME: data-table

Resources:
  SamSampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'functions/sample_function/lambda_function.zip'
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::569113468865:role/lambda_dynamo
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            #Schedule: cron(0 * * * ? *)

Transform: AWS::Serverless-2016-10-31
