AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda function by using AWS SAM.
Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME:
          Ref: SamSampleDynamoTable
    MemorySize: 256
    Runtime: python3.6
    Timeout: 15
Resources:
  SamSampleDynamoTable:
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
    Type: AWS::Serverless::SimpleTable
  SamSampleLambda:
    Properties:
      CodeUri: s3://yueguchi-sam-sample/7ad4a790181db86b735159b648361c05
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::569113468865:role/lambda_dynamo
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
