AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda function by using AWS SAM.

Globals:
  Function:
    Runtime: python3.6
    Timeout: 15
    MemorySize: 256
    Environment:
     Variables:
       TABLE_NAME: !Ref SamSampleDynamoTable

Resources:
  SamSampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 'functions/sample_function/lambda_function.zip'
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::569113468865:role/lambda_dynamo

  SamSampleDynamoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Transform: AWS::Serverless-2016-10-31
