AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda function by using AWS SAM.
Resources:
  SamSampleLambda:
    Properties:
      CodeUri: s3://yueguchi-sam-sample/c5dbb6f716f3067bcedff28119f5bd71
      Handler: functions/lambda_function.lambda_handler
      Role: arn:aws:iam::569113468865:role/lambda_dynamo
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
